MiT-HEP/ChargedHiggs

dat/config.dat, interface/AnalysisChargedHiggsHW.hpp, interface/AnalysisChargedHiggsMET.hpp, interface/AnalysisChargedHiggsTauNu.hpp, interface/AnalysisChargedHiggsTopBottom.hpp, interface/Event.hpp, src/AnalysisChargedHiggsHW.cpp, src/AnalysisChargedHiggsMET.cpp, src/AnalysisChargedHiggsTauNu.cpp, src/AnalysisChargedHiggsTopBottom.cpp, src/PreselectionAnalysis.cpp
Added analysis modules for the different decay channels:
- Charged Higgs  to tau nu
- Charged Higgs to HW
- Charged Higgs to chargino neutralino
- Charged Higgs to top bottom
The latter three are only dummy modules, event selection and histograms still need to be added
=> Added analysis modules

Makefile, Readme.md, dat/config.dat, interface/Event.hpp, interface/Loop.hpp, interface/PU.hpp, interface/Smearer.hpp, interface/Weight.hpp, python/Loop.py, python/ParseDat.py, python/puDistributions.py, script/submit.py, src/Event.cpp, src/EventVariablesAnalysis.cpp, src/Loop.cpp, src/Output.cpp, src/PU.cpp, src/PreselectionAnalysis.cpp, src/Smearer.cpp, src/Weight.cpp
Support for:
* 1D Pileup reweighting #1 
* RD Pilelup reweighting #1 
* systematic smearings for pileup model
Tests performed:
* Compilation
* Execution (1D)
* Execution time (1D) 
* works without PU reweight. (maybe too verbose if systematics on PU are on)
Test missing:
* Final check that distributions are fine.
* Tests for RD reweighting (low priority)
=> added PU reweight.

dat/config.dat, dat/mc_database.txt, interface/AnalysisBase.hpp, python/ParseDat.py, src/AnalysisBase.cpp, src/AnalysisChargedHiggsTauNu.cpp
* added new samples to the config file. 
* update mc database accordingly.
* made configurable labels per analysis.
* removed not necessary .c_str()
=> added new samples to the config file. made configurable labels.

src/AnalysisChargedHiggsTauNu.cpp
Modified cutflow for the tau nu channel
=> Charged higgs tau nu mod fix

dat/config.dat, dat/mc_database.txt
=> Configuration fix

interface/Event.hpp, interface/Lepton.hpp, src/Event.cpp, src/EventVariablesAnalysis.cpp
=> add get object

interface/AnalysisBase.hpp, interface/Output.hpp, interface/Tau.hpp, script/optimization.py, src/AnalysisBase.cpp, src/Loop.cpp, src/Output.cpp, src/TauOptimization.cpp
* added support for TH2D
* added script for dumping optimization histo
* add v6 variables for tau (iso2, id_ele, id_muon)
=> Topic th2 d

Makefile, interface/AnalysisBase.hpp, script/submit.py, src/AnalysisChargedHiggsHW.cpp, src/AnalysisChargedHiggsMET.cpp, src/AnalysisChargedHiggsTauNu.cpp, src/AnalysisChargedHiggsTopBottom.cpp, src/AnalysisChargedHiggsZW.cpp
* fix return code using a define in AnalysisBase. close #19 
* force makefile to recompile everything as default behaviour.
* add support for pending jobs in script/submit.py, and bug fix in resubmission.
=> Return Code

src/Event.cpp
* missed a (1-..) in M_T calculations.
@kfiekas can you check that Mt is know correct ? 
@xmniu this may be interesting also for you
=> fix mt variable

interface/Event.hpp, interface/Jet.hpp, interface/Lepton.hpp, interface/Tau.hpp, src/Event.cpp, src/Jet.cpp, src/Lepton.cpp, src/Tau.cpp
We should not rely on the selection in the ntuples (that can be also looser due to synchr production)
*adding pt requirement on Tau (41 GeV)
* adding iso requirement for taus ( deltaBeta <1.5 ) 
*adding pT reqirement for leptons (for the moment symmetric 15 GeV)
* creating central jets (eta 2.4)
=> Object Requirements

dat/config.dat, interface/AnalysisBase.hpp, src/AnalysisBase.cpp, src/AnalysisChargedHiggsTauNu.cpp
Added plots to study angular cuts between jets, tau and MET
=> Angular cuts for tau nu final state 

interface/Jet.hpp, script/combine.py, src/Tau.cpp
* fix tau > 41. 
* fix Central Jets return. 
* Remove work around 53X for combine.
=> Small bugs

Makefile, dat/branches.txt, dat/config.dat, dat/configTmva.dat, datacards/cms_datacard_chhiggs_taunu.txt, interface/AnalysisBase.hpp, interface/Event.hpp, interface/JSON.hpp, interface/Output.hpp, interface/TmvaTrainer.hpp, python/Loop.py, src/JSON.cpp, src/Loop.cpp, src/Output.cpp, src/TmvaTrainer.cpp
Example on how to write a tmva trainer.
* added support for tree in the output file
* train a bdt to discriminate between signal and bkg
Missing: configuration if we want to have different usage.
Missing: weights directory name.
=> TMVA and Trees

script/submit.py
silent rm of job control files.
=> Submission script

Makefile, dat/branches.txt, dat/config.dat, dat/configQCDPurity.dat, dat/configTagAndProbe.dat, dat/mc_database_v1.1.txt, interface/Event.hpp, interface/GeneralFunctions.hpp, interface/Lepton.hpp, interface/Met.hpp, interface/TagAndProbe.hpp, interface/Tau.hpp, interface/Trigger.hpp, script/optimization.py, script/submit.py, script/tagprobeplots.py, script/triggerplots.py, src/AnalysisChargedHiggsEWKEmbedding.cpp, src/AnalysisChargedHiggsQCDPurity.cpp, src/Event.cpp, src/Loop.cpp, src/TagAndProbe.cpp, src/Tau.cpp
* implementing changes to run on ntuples produced with MiniAODv2
* #35
=> Topic 7 4 12

Readme.md, dat/branches.txt, dat/config.dat, dat/configQCDPurity.dat, interface/Corrector.hpp, interface/Event.hpp, interface/Loop.hpp, interface/MetPhiCorrector.hpp, python/Loop.py, python/ParseDat.py, script/metPhiCorrections.py, script/tagprobeplots.py, src/AnalysisChargedHiggsQCDPurity.cpp, src/Loop.cpp, src/MetPhiCorrector.cpp
implementing first version of met phi corrector.
=> MetPhi Corrector

test/plotdat/Readme.md, test/plotdat/chhiggs_cutflow.txt, test/plotdat/chhiggs_met.txt, test/plotdat/chhiggs_metqcd.txt, test/plotdat/chhiggs_mt.txt, test/plotdat/chhiggs_mtmc.txt, test/plotdat/chhiggs_njets.txt, test/plotdat/chhiggs_none_template.txt, test/plotdat/chhiggs_tau1pt.txt, test/plotdat/plotall.py, test/plotdat/tmva_bdt0.txt, test/plotdat/tmva_bdt1.txt, test/plotdat/tmva_cutflow.txt, test/plotdat/tmva_mt.txt
=> Plot Style files 

dat/configSync.dat, interface/AnalysisChargedHiggsSync.hpp, interface/Event.hpp, interface/GeneralFunctions.hpp, interface/Jet.hpp, interface/Lepton.hpp, script/submit.py, src/AnalysisChargedHiggsSync.cpp, src/AnalysisChargedHiggsTauNu.cpp, src/Event.cpp
part I:
* dump information for sync purposes.
=> Synchronization

aux/RMet80.txt, interface/Smearer.hpp, script/updatestatus.py, src/Loader.cpp, src/PurityFit.cpp, src/PurityFitAnalytic.cpp
improvements in the QCD fit. And Syst bug fixes
=> Improvements

script/triggerplots.py
* changes that we probably want in the trigger met turn on curves.
=> trigger script

script/bwsTB.py
A script for building workspace for top bottom
=> Combine Top Bottom

interface/AnalysisBase.hpp, interface/Tau.hpp, src/AnalysisChargedHiggsTopBottom.cpp, src/Loader.cpp, src/Tau.cpp
Should be the desired configuration for both taunu and topbottom.
=> tau configuration

interface/AnalysisBase.hpp, interface/Output.hpp, src/Output.cpp
Added support for arrays of fixed and variable Length in MiniTrees:
usage:
Branch("tree","bname","d", 10 ) ; // or variable length up to 10 Branch("tree","bname","d", 10 ,"otherbranchname") ;
SetTreeVar("bname" , 0 , 0.2) ; SetTreeVar("bname" , 1 , 1.3) ;
=> Arrays in MiniTree

dat/config.dat, interface/AnalysisBase.hpp, interface/Loop.hpp, interface/Output.hpp, python/ParseDat.py, src/Output.cpp
At the very end, it may be convient to switch off many histograms to make it fast.
=> introducing final histos

.gitignore, interface/AnalysisBase.hpp, script/drawSyst.py, src/AnalysisBase.cpp, src/Loop.cpp
To run on multi primary datasets:
should be enough to (in the dat file):
SetMultiPrimaryDataset()
AddLabel("SingleElectron"),AddLabel("SingleMuon")
To be tested
=> multi primary datasets and drawSyst

interface/AnalysisBase.hpp, interface/AnalysisChargedHiggsEWKPurity.hpp, interface/AnalysisChargedHiggsQCDPurity.hpp, interface/AnalysisChargedHiggsTauNu.hpp, interface/Event.hpp, src/AnalysisChargedHiggsEWKPurity.cpp, src/AnalysisChargedHiggsQCDPurity.cpp, src/AnalysisChargedHiggsTauNu.cpp, src/Event.cpp
* making all the taunu related analysis inherits from taunu.
=> upgrading tau nu.

aux/tb_1l_hiMass_BDT.weights.xml, aux/tb_1l_loMass_BDT.weights.xml, aux/tb_1l_meMass_BDT.weights.xml, aux/tb_2l_hiMass_BDT.weights.xml, aux/tb_2l_loMass_BDT.weights.xml, aux/tb_2l_meMass_BDT.weights.xml
=> New training -- split in three mass regions

interface/AnalysisChargedHiggsTopBottom.hpp, interface/Lepton.hpp, src/AnalysisChargedHiggsTopBottom.cpp
@amarini 
you can merge if you like the changes in interface/Lepton.hpp
=> Top bot v8

interface/AnalysisBase.hpp, interface/AnalysisChargedHiggsTauNu.hpp, interface/Lepton.hpp, src/AnalysisChargedHiggsTopBottom.cpp, src/AnalysisHmumu.cpp, src/Loader.cpp
* adding configuration for veto/loose electrons
=> making veto/loose lepton configurable

dat/catalog/2017.moriond/topbottom.dat, dat/configTopBot_1l.dat, dat/configTopBot_2l.dat, dat/topBot.2017.dat, makeAllMARCH5, makeDataCard, script/bwsTB.py, src/AnalysisChargedHiggsTopBottom.cpp
configuration as in Pietro's talk and AN
=> Top bot v13

dat/configHmumu.dat, python/hmm.py, script/combine.py, script/makeFinalPlotsHmm.py, src/AnalysisHmumu.cpp, test/cms_datacard_hmumu_cat13.txt
* Change ordering between ttHHadr and ttH Lep
=> adding Quantile Mapping for plots

src/Loader.cpp
@amarini 
Do not merge, unless you want the tau analysis to change
=> set the leptonVeto and tauID for the tb leptonic analysis

dat/configQG.dat, interface/AnalysisQG.hpp, src/AnalysisQG.cpp
=> implementing changes in qg v1.

.travis.yml, configure, dat/configQCDPurity.2016.dat, dat/configTauNu.2016.dat, dat/taunu.dat, interface/AnalysisChargedHiggsQCDPurity.hpp, interface/AnalysisChargedHiggsTauNu.hpp, script/Hmumu/makeFinalPlotsHmm.py, script/Hmumu/sobweighted/adjust.py, script/makeCombinePlots.py, script/makeNLLPlots.py, script/makePvalPlots.py, src/AnalysisChargedHiggsQCDPurity.cpp, src/AnalysisChargedHiggsTauNu.cpp, src/PurityFit.cpp, src/PurityFitAnalytic.cpp
TauNu:
* starting to update the analysis
Hmm:
* refining plots scripts for paper
=> Taunu and hmm

interface/AnalysisChargedHiggsTBfullHad.hpp, interface/FatJet.hpp, src/AnalysisChargedHiggsTBfullHad.cpp, src/Loader.cpp
change tau32 cut 0.81 -> 0.67
add subjet csv check; 
triggers updated; 
fix rapidity cut
=> tau32 cut change; subjet csv check; triggers updated; fix rapidity cut

interface/BTagCalibrationStandalone.hpp, python/buildtest.py, src/BTagCalibrationStandalone.cpp
Use unique ptr instead of auto_ptr
=> unique_ptr

python/buildtest.py, script/Hmumu/plotValidation.py
=> Validation Summary
